/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consumer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author f_gar
 */
public class Editar_alumno extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar_alumno
     */
    public Editar_alumno() {
        initComponents();
    }
    
//    public void onAlumnoSelected(String matricula, String nombre, String a_paterno, String a_materno, String num_telefono, String correo, String generacion, String carrera, String grupo, String grado) {
//        // Aquí puedes utilizar los datos recibidos para lo que necesites
//        // Por ejemplo, puedes mostrarlos en etiquetas o campos de texto del JFrameOtro
//        txt_Amatricula.setText(matricula);
//        txt_Anombre.setText(nombre);
//        txt_Aap.setText(a_paterno);
//        txt_Aam.setText(a_materno);
//        txt_Anumtelefonico.setText(num_telefono);
//        txt_Acorreo.setText(correo);
//        txt_Ageneracion.setText(generacion);
//        txt_Acarrera.setText(carrera);
//        txt_Agrupo.setText(grupo);
//        txt_Agrado.setText(grado);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Amatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Anombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Aap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Aam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Anumtelefonico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Acorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Ageneracion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Acarrera = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Agrupo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Agrado = new javax.swing.JTextField();
        btn_regresar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar alumno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));
        jPanel1.add(txt_Amatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, -1));

        jLabel2.setText("Matricula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 102, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 102, -1));
        jPanel1.add(txt_Anombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 180, -1));

        jLabel4.setText("Apellido Paterno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        jPanel1.add(txt_Aap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 180, -1));

        jLabel5.setText("Apellido Materno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));
        jPanel1.add(txt_Aam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, -1));

        jLabel6.setText("Numero Telefonico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));
        jPanel1.add(txt_Anumtelefonico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 180, -1));

        jLabel7.setText("Correo Electronico");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));
        jPanel1.add(txt_Acorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, -1));

        jLabel8.setText("Generacion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));
        jPanel1.add(txt_Ageneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 180, -1));

        jLabel9.setText("Carrera");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));
        jPanel1.add(txt_Acarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 180, -1));

        jLabel10.setText("Grupo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 43, -1));
        jPanel1.add(txt_Agrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 180, -1));

        jLabel11.setText("Grado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 43, -1));
        jPanel1.add(txt_Agrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 180, -1));

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 115, -1));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 115, 30));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 110, 760, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Listado_alumnos L = new Listado_alumnos();
        L.setVisible(true);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        
      
           
    }//GEN-LAST:event_btn_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar_alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Aam;
    private javax.swing.JTextField txt_Aap;
    private javax.swing.JTextField txt_Acarrera;
    private javax.swing.JTextField txt_Acorreo;
    private javax.swing.JTextField txt_Ageneracion;
    private javax.swing.JTextField txt_Agrado;
    private javax.swing.JTextField txt_Agrupo;
    private javax.swing.JTextField txt_Amatricula;
    private javax.swing.JTextField txt_Anombre;
    private javax.swing.JTextField txt_Anumtelefonico;
    // End of variables declaration//GEN-END:variables
}
